config/routes.rb
Rails.application.routes.draw do
  # Just base CRUD nested resources
  resources :targets do
    resources :schedules do
      resources :pings
    end
  end

  # Custom URLs
  get 'pings/history' => 'pings#history', as: :pings_history

  # Root request
  root to: "home#index"

  # CRUD Resources  resources :targets
  # Devise session manager
  devise_for :users
end

app/models/target.rb
class Target < ActiveRecord::Base
  # Associations
  belongs_to :user
  has_many :schedules
  has_many :pings

  # Rails validations
  validates :url, presence: true, length: { in: 10..255 }, on: [:create, :update]

  # Associations validations
  validates_presence_of :user_id, on: [:create, :update]

  # Return it name
  def name
    # Base vars
    aux_name = self.url
    str_before_name = '//'
    name_starts_at = aux_name.index(str_before_name)+str_before_name.length
    aux_name[name_starts_at..url.index('.')-1]
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @targets = Target.all
    respond_with(@targets)
  end

  def show
    @pings = @target.pings
    respond_with(@target)
  end

  def new
    @target = Target.new
    respond_with(@target)
  end

  def edit
  end

  def create
    @target = Target.new(target_params)
    @target.user_id = @current_user.id
    flash[:notice] = 'Target created successfully' if @target.save
    respond_with(@target)
  end

  def update
    @target.update(target_params)
    respond_with(@target)
  end

  def destroy
    @target.destroy
    respond_with(@target)
  end

  private
    def set_target
      @target = Target.find(params[:id])
    end

    def target_params
      params.require(:target).permit(:url, :user_id)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.slim
= form_for @target do |f|
  - if @target.errors.any?
    #error_explanation
      h2 = "#{pluralize(@target.errors.count, "error")} prohibited this target from being saved:"
      ul
        - @target.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :url
    = f.text_field :url
  .actions = f.submit 'Save'

app/views/targets/edit.html.slim
h1 Editing target

== render 'form'

= link_to 'Show', @target
'|
= link_to 'Back', targets_path

app/views/targets/index.html.slim
h1 Listing targets

.table-responsive
  table.table.table-hover
    tr
      th Name
      th Url
      th User
      th
      th
      th
      th

    tbody
      - @targets.each do |target|
        tr
          td = target.name
          td = target.url
          td = target.user.name
          td = link_to 'AddSchedule', new_target_schedule_path(target)
          td = link_to 'Show', target
          td = link_to 'Edit', edit_target_path(target)
          td = link_to 'Destroy', target, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

= link_to 'New Target', new_target_path

app/views/targets/new.html.slim
h1 New target

== render 'form'

= link_to 'Back', targets_path

app/views/targets/show.html.slim
p
  strong User:
  = " #{@target.user.name}"
p
  strong Url:
  = " #{@target.url}"

= link_to 'Add schedules ', new_target_schedule_path(@target)
'|
= link_to 'Edit ', edit_target_path(@target)
'|
= link_to 'Back', targets_path

=render 'pings/list'