config/routes.rb
Rails.application.routes.draw do
  # Just base CRUD nested resources
  resources :targets do
    resources :schedules do
      resources :pings
    end
  end

  # Custom URLs
  get 'pings/history' => 'pings#history', as: :pings_history

  # Root request
  root to: "home#index"

  # CRUD Resources  resources :targets
  # Devise session manager
  devise_for :users
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  # Associations
  belongs_to :target
  has_many :pings

  # Check it for each target
  before_validation :check_uniqueness

  # Rails validations
  validates :hour, presence: true, numericality: {greater_than:0, less_than:24}, on: [:create, :update]

  # Association validations
  validates_presence_of :target_id, on: [:create, :update]

  def check_uniqueness
    similar_schedule = Schedule.where.not(id:self.id).where(target_id: self.target_id, hour: self.hour).take
    if similar_schedule
      self.errors.add('hour', 'it schedule hour is duplicated to it target')
      raise ActiveRecord::Rollback
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :setup_nested
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @schedules = Schedule.where(target_id: params[:target_id])
    respond_with(@schedules)
  end

  def show
    respond_with(@schedule)
  end

  def new
    @schedule = Schedule.new
    respond_with(@schedule)
  end

  def edit
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.save
    respond_with(@target, @schedule)
  end

  def update
    @schedule.update(schedule_params)
    respond_with(@target, @schedule)
  end

  def destroy
    @schedule.destroy
    respond_with(@target, @schedule)
  end

  private
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def schedule_params
      params.require(:schedule).permit(:hour).merge(target_id:params[:target_id])
    end

    def setup_nested
      @target = Target.find(params[:target_id])
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.slim
= form_for [@target,@schedule] do |f|
  - if @schedule.errors.any?
    #error_explanation
      h2 = "#{pluralize(@schedule.errors.count, "error")} prohibited this schedule from being saved:"
      ul
        - @schedule.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :hour
    = f.text_field :hour
  .actions = f.submit 'Save'

app/views/schedules/edit.html.slim
h1 Editing schedule

== render 'form'

= link_to 'Show', @schedule
'|
= link_to 'Back', target_schedules_path(@target)

app/views/schedules/index.html.slim
h1 Listing schedules

table
  thead
    tr
      th Hour
      th Target
      th
      th
      th

  tbody
    - @schedules.each do |schedule|
      tr
        td = schedule.hour
        td = schedule.target.url
        td = link_to 'Show', target_schedule_path(@target, schedule)
        td = link_to 'Edit', edit_target_schedule_path(@target, schedule)
        td = link_to 'Destroy', [@target, schedule], data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Schedule', new_target_schedule_path(@target)

app/views/schedules/new.html.slim
h1 New schedule

== render 'form'

= link_to 'Back', target_schedules_path(@target)

app/views/schedules/show.html.slim
p
  strong Hour:
  = @schedule.hour
p
  strong Target:
  = @schedule.target.url

= link_to 'Edit', edit_target_schedule_path(@target, @schedule)
'|
= link_to 'Back', target_schedules_path(@target)