config/routes.rb
Rails.application.routes.draw do
  # Just base CRUD nested resources
  resources :targets do
    resources :schedules do
      resources :pings
    end
  end

  # Custom URLs
  get 'pings/history' => 'pings#history', as: :pings_history

  # Root request
  root to: "home#index"

  # CRUD Resources  resources :targets
  # Devise session manager
  devise_for :users
end

app/models/ping.rb
class Ping < ActiveRecord::Base
  # Associations
  belongs_to :target
  belongs_to :schedule

  # Rails validations
  validates :http_code, numericality: {}
  validates_inclusion_of :http_code, in: HttpConst.codes.values, on: [:create, :update]

  # Association validations
  validates_presence_of :target_id
  validates_presence_of :schedule_id
end

app/controllers/pings_controller.rb
class PingsController < ApplicationController
  before_action :setup_nested, except: :history
  before_action :set_ping, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pings = @target.pings
    respond_with(@target, @schedule, @pings)
  end

  def history
    @pings = Ping.all
    @targets = @current_user.targets
  end

  def show
    respond_with(@target, @schedule, @ping)
  end

  def new
    @ping = Ping.new
    respond_with(@target, @schedule, @ping)
  end

  def edit
  end

  def create
    @ping = Ping.new(ping_params)
    @ping.save
    respond_with(@target, @schedule, @ping)
  end

  def update
    @ping.update(ping_params)
    respond_with(@target, @schedule, @ping)
  end

  def destroy
    @ping.destroy
    respond_with(@target, @schedule, @ping)
  end

  private
    def setup_nested
      @target = Target.find(params[:target_id])
      @schedule = Schedule.find(params[:schedule_id])
    end

    def set_ping
      @ping = Ping.find(params[:id])
    end

    def ping_params
      params.require(:ping).permit(:http_code, :schedule_id, :target_id)
    end
end

app/helpers/pings_helper.rb
module PingsHelper
end

app/views/pings/_form.html.slim
= form_for [@target, @schedule, @ping] do |f|
  - if @ping.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ping.errors.count, "error")} prohibited this ping from being saved:"
      ul
        - @ping.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :http_code
    = f.text_field :http_code
  .actions = f.submit 'Save'

app/views/pings/_list.html.slim
.row
  table.table.table-hover
    thead
      tr class="info"
        th Horary
        th Target name
        th Target URL
        th HTTP Code
        th HTTP Code Name
        th HTTP Code meaning

    tbody
      - @pings.each do |ping|
        -background='success' if HttpConst.success?ping.http_code
        -background='info' if HttpConst.redirect?ping.http_code
        -background='warning' if HttpConst.client_error?ping.http_code
        -background='danger' if HttpConst.server_error?ping.http_code
        tr class="#{background}"
          td = ping.created_at.strftime('%d/%m/%y - %H:%M')
          td = ping.target.name
          td = ping.target.url
          td = ping.http_code
          td = HttpConst.code_name ping.http_code
          td = "TODO add meaning to the locales files"

app/views/pings/edit.html.slim
h1 Editing ping

== render 'form'

= link_to 'Show', [@target, @schedule, @ping]
'|
= link_to 'Back', target_schedule_pings_path(@target, @schedule)

app/views/pings/history.html.slim
.row
  h2 Listing the PingsHistory
=render 'list'

app/views/pings/index.html.slim
h1 Listing pings
=render 'list'
= link_to 'New Ping', target_schedule_pings_path(@target, @schedule)

app/views/pings/new.html.slim
h1 New ping

== render 'form'

= link_to 'Back', pings_path

app/views/pings/show.html.slim
p
  strong Http code:
  = @ping.http_code
p
  strong Scheduled:
  = @ping.scheduled
p
  strong Target:
  = @ping.target

= link_to 'Edit', edit_ping_path(@ping)
'|
= link_to 'Back', pings_path